In [188]:
import pandas as pd
import os
def processMain(EXP, N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("main_N"+str(N)+"_")]
    print(prefixed)
    # dfs_list = [pd.read_csv(file, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    # print(dfs_list[0])
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(df)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output
    
def processLazy(EXP, N):
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("lazyDelay_N"+str(N)+"_")]
    dfs_list = []
    for filename in prefixed:
        split = filename.split("_")[-1].split(".")[0]
        # print(split)  
        
        df = pd.read_csv(filename, sep=';', names=['num_cases','total_time','b','ObjVal','z','x_sol'], header=None)
        df['Ins'] = split
        dfs_list.append(df)
        # print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    return output

EXP = 'main'
N =30
df_main = processMain(EXP, N)
df_main
df_lazy = processLazy(EXP, N)
df_lazy

df_lazy.total_time.mean()

# print(df_main.total_time.sum()+3600)/10
df_main
# (df_main.total_time.sum()+3600*2)/10
# (df_lazy.total_time.sum()+3600)/10
# df_lazy
# df_main

['main_N30_4.txt', 'main_N30_5.txt', 'main_N30_7.txt', 'main_N30_2.txt', 'main_N30_3.txt', 'main_N30_1.txt', 'main_N30_10.txt', 'main_N30_8.txt', 'main_N30_9.txt']

,iiter,total_time,b,ObjVal,x_sol,Ins
0,-1,1.219656,10,397.000000,[ 0 1 4 7 26 91 126 132 152 159],4
1,-1,14.366338,10,321.390804,[ 1 2 34 37 38 39 50 53 69 176],5
2,-1,0.377611,10,388.000000,[ 0 1 2 3 4 5 6 9 133 164],7
3,-1,39.781799,10,463.643875,[ 0 1 2 15 17 55 59 101 110 119],2
4,-1,1.750650,10,275.000000,[ 0 1 2 3 4 76 79 84 91 141],3
5,-1,2.249137,10,564.164062,[ 0 1 2 3 4 5 6 32 63 85],1
6,-1,1.211894,10,688.000000,[ 0 1 2 25 38 52 67 70 98 153],10
7,-1,0.410036,10,330.000000,[ 0 1 2 3 4 5 6 39 75 172],8
8,-1,11.285004,10,371.078102,[ 0 1 2 3 127 134 146 155 161 163],9

In [148]:
def processSAA(N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SAA_N"+str(N)+"_")]
    print(prefixed)
    dfs_list = [pd.read_csv(file, sep=';', names=['iiter','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    # print(dfs_list[0])
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output
N =40
df_SAA = processSAA(N)
# (df_SAA[df_SAA.iiter ==50000]['total_time'].sum()+3600)/10
df_SAA

['SAA_N40_4.txt', 'SAA_N40_5.txt', 'SAA_N40_7.txt', 'SAA_N40_6.txt', 'SAA_N40_2.txt', 'SAA_N40_3.txt', 'SAA_N40_10.txt', 'SAA_N40_1.txt', 'SAA_N40_8.txt', 'SAA_N40_9.txt']

,iiter,total_time,b,ObjVal,x_sol
0,500,3.367913,10,335.000478,[ 2 4 29 49 93 116 131 250 274 243]
1,5000,24.050526,10,335.000102,[ 2 4 29 49 93 116 131 250 274 243]
2,50000,460.442167,10,334.421429,[ 2 4 29 49 93 116 131 250 274 243]
3,500,2.574390,10,387.650520,[ 2 8 60 61 81 169 170 153 65 124]
4,5000,14.714371,10,387.115019,[ 2 8 60 61 81 169 170 153 65 124]
5,50000,185.909566,10,387.494823,[ 2 8 60 61 81 169 170 153 65 124]
6,500,0.609542,10,168.000000,[ 0 1 2 3 4 5 234 200 260 274]
7,5000,6.194051,10,168.000000,[ 0 1 2 3 4 5 234 200 260 274]
8,50000,62.387255,10,168.000000,[ 4 150 188 234 236 25 200 80 260 274]
9,500,1.461885,10,264.376147,[ 0 3 4 5 118 236 137 292 250 270]
10,5000,20.432230,10,264.074821,[ 0 2 3 5 9 118 236 125 292 250]
11,50000,126.856182,10,264.083107,[ 3 5 9 10 72 118 236 292 250 270]
12,500,2.096035,10,497.599447,[ 0 2 4 57 170 253 272 289 299 165]
13,5000,20.380715,10,497.221491,[ 0 2 4 57 170 172 272 289 299 165]
14,50000,180.243668,10,497.055389,[ 0 2 4 57 170 253 272 289 299 165]
15,500,2.186331,10,457.568636,[ 1 2 6 50 60 155 157 135 177 139]
16,5000,12.166740,10,454.665339,[ 1 2 6 50 60 155 157 135 177 139]
17,50000,158.457942,10,454.807203,[ 1 2 6 50 60 155 157 135 177 139]
18,500,6.968200,10,483.363198,[ 0 1 5 17 106 292 174 234 249 299]
19,5000,107.712835,10,486.222896,[ 0 1 5 17 106 292 174 234 249 299]
20,50000,1930.248023,10,486.394946,[ 0 1 5 17 106 292 174 234 249 299]
21,500,2.452031,10,509.208228,[ 0 1 40 90 320 277 205 243 59 254]
22,5000,26.219072,10,509.256589,[ 0 1 40 90 320 277 205 243 59 254]
23,50000,230.153905,10,509.240842,[ 0 1 40 90 320 277 205 243 59 254]
24,500,0.997012,10,584.954533,[ 0 1 2 3 39 40 44 225 210 211]
25,5000,9.512232,10,584.990651,[ 0 1 2 3 39 40 44 225 210 211]
26,50000,100.390362,10,584.993603,[ 0 2 44 152 230 61 225 32 144 211]
27,500,2.227980,10,459.287393,[ 0 50 53 71 25 48 36 308 228 232]
28,5000,27.874709,10,458.813405,[ 0 50 53 71 25 48 36 308 228 232]
29,50000,549.698409,10,458.184346,[ 0 50 53 71 25 279 48 36 308 228]

In [152]:
df_main

,iiter,total_time,b,ObjVal,x_sol
0,-1,35.973455,10,486.490680,[ 0 1 5 17 106 174 234 249 292 299]
1,-1,6.059924,10,585.000000,[ 0 1 2 3 4 44 145 154 181 225]
2,-1,974.121795,10,458.215447,[ 0 25 36 48 50 53 71 186 228 308]
3,-1,0.377572,10,168.000000,[ 0 1 2 3 4 5 6 200 234 260]
4,-1,18.817928,10,264.202148,[ 0 3 5 9 118 122 236 250 292 294]
5,-1,3.053638,10,497.000000,[ 0 2 4 57 165 170 253 272 289 299]
6,-1,138.772180,10,454.663145,[ 1 2 6 50 60 135 139 155 157 177]
7,-1,36.247280,10,509.265382,[ 0 1 40 59 90 205 243 254 277 320]

In [63]:
df_SAA[(df_SAA.num_cases ==50000)&(df_SAA.b==2)]

    num_cases  total_time  b      ObjVal    x_sol
6       50000   26.058902  2   76.000000  [ 2 30]
10      50000   25.790386  2   76.000000  [ 2 30]
18      50000   76.267384  2  277.000000  [ 0 18]
22      50000   76.489195  2  277.000000  [ 0 18]
30      50000   61.703715  2  241.078650  [ 4 20]
34      50000   62.795576  2  241.078650  [ 4 20]
42      50000   45.880813  2   66.323960  [ 4 21]
46      50000   46.525756  2   66.323960  [ 4 21]
54      50000   31.046645  2  192.787031  [ 0 18]
58      50000   30.830447  2  192.787031  [ 0 18]

In [64]:
df_SeqSampling

,num_cases,total_time,b,ObjVal,x_sol,var,opt_gap,iter,para
0,49,1.594740,2,35.937095,[4 6],1.203329e+02,6.331572,23,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
1,49,1.387805,2,173.646302,[ 0 22],2.525407e-27,56.000000,20,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
2,49,0.654536,2,76.000000,[ 2 30],1.811915e-30,2.000000,7,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
3,49,0.815751,2,277.000000,[ 0 18],4.529787e-31,1.000000,9,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
4,49,18.419930,2,232.120182,[4 5],4.798603e+01,57.561440,67,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."