In [7]:
import csv 
import numpy as np



# print(edge)
# arc = np.array([[1,2]])
# edge = np.concatenate((edge, arc), axis=0)
# print(edge)
# edge = np.empty([[]])
def processInputFile(alg, testSet):
    print("Processing network instance", testSet)
    # fileName = "/Users/dinguyen/Desktop/Local Documents/GitHub/Paper5/NewCSVFeb24/"+testSet+"_"+str(i)+".csv"
    fileName = "./"+alg+".csv"
    # Desktop/Local Documents/GitHub/Paper5/TestInstances/CSV_TestInstances/N25/N25_108.csv
    # N25/N25_108.csv
    instance = []
    iteration = []
    time = []
    budget = []
    Obj = []
    interdiction = []
    with open(fileName, newline='\n') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=';')
        count = 0
        # print("d ", d)
        for row in spamreader:
            print(', '.join(row))
            in
#             count +=1 
#             # print(count," ", len(row), " ", row)
#             if count == 1:
#                 Len = int(row[0])
#             if count == 2:
#                 origin = int(row[0])
#             if count == 3:
#                 destination = int(row[0])
#             if count >= 5: 
#                 arc = np.array([[int(row[0]), int(row[1])]])
#                 # print("Shape arc: ", np.shape(arc))
#                 # print("arc ", arc)
#                 edge = np.concatenate((edge, arc), axis=0)
#                 # print(row[2])
#                 d = np.append(d, float(row[4]))
#                 cL_orig = np.append(cL_orig, float(row[2]))
#                 cU_orig = np.append(cU_orig, float(row[3]))
                # print(d)
    return 0

In [8]:
testSet = 100
all_instances = range(5)
methods = ['lazyDelay']
processInputFile('lazyDelay', testSet)

Processing network instance 100
﻿Instance,iteration,time,budget,Obj,interdiction
1,1,0.124714136,2,163,[0 1]
1,2,42.17105103,2,163,[0 1]
1,3,77.70317316,2,218,[  23 1515]
1,4,80.29138899,2,197.1943359,[1515 2247]
1,5,82.93993711,2,193.3637695,[1515 2247]
1,6,152.5827761,2,192.5819092,[1515 2247]
1,7,272.368669,2,192.541748,[1515 2247]
1,8,503.6127529,2,192.5125122,[1515 2247]
1,9,949.9057763,2,197.1943359,[  23 2247]
1,10,983.0485461,2,194.9875031,[  23 2247]
1,11,1881.867946,2,194.4635773,[  23 2247]
1,12,3424.534329,2,194.1081047,[  23 2247]
2,1,0.124168158,2,122,[1 2]
2,2,5.315118074,2,139,[0 1]
2,3,5.595731974,2,187,[  0 115]
2,4,5.87972188,2,172,[2641 2890]
2,5,6.191280127,2,177.9375,[   0 2890]
2,6,11.774575,2,176.390625,[   0 2890]
2,7,22.44579315,2,174.84375,[   0 2890]
2,8,43.66870189,2,173.6835938,[   0 2890]
2,9,86.30618811,2,172.9101563,[   0 2890]
2,10,171.5291891,2,169,[ 115 2890]
2,11,177.8854461,2,168.8225098,[ 115 2890]
2,12,349.3514061,2,168.8011475,[ 115 2890]
2,13,692.893249,2,168.6935425,[ 115 2890]
2,14,1379.313787,2,168.3941193,[ 115 2890]
2,15,2758.203753,2,172.4274902,[   0 2890]
2,16,2856.850629,2,172.2501678,[   0 2890]
3,1,0.117728949,2,199,[1 2]
3,2,1.300026894,2,233,[0 1]
3,3,1.446441889,2,272,[  0 224]
3,4,1.59489584,2,227.6875,[   0 1471]
3,5,11.63446188,2,226.984375,[   0 1471]
3,6,22.69507289,2,226.0625,[   0 1471]
3,7,44.84180284,2,224.9726562,[   0 1471]
3,8,89.07192183,2,224.3687744,[   0 1471]
3,9,178.0243337,2,240.7871704,[   0 3012]
3,10,184.5316927,2,233,[  0 280]
3,11,191.0989788,2,231.5127563,[  0 209]
3,12,197.6540308,2,228.7588501,[  0 209]
3,13,376.4603288,2,227.9682617,[  0 280]
3,14,389.4610057,2,227.4356079,[   0 3012]
3,15,402.4994156,2,226.9377441,[   0 3012]
3,16,761.2401967,2,226.6378479,[   0 3012]
3,17,1482.433265,2,226.3538208,[   0 3012]
3,18,2937.172977,2,226.0841827,[   0 3012]
4,1,0.122399092,2,94,[1 2]
4,2,1.251930952,2,125,[0 1]
4,3,1.401399136,2,149,[ 0 58]
4,4,1.552146912,2,172,[   0 1685]
4,5,1.697005033,2,142,[   0 1685]
4,6,43.94940281,2,141.875,[   0 1685]
4,7,86.38694191,2,141.5625,[   0 1685]
4,8,165.2382059,2,141.1484375,[   0 1685]
4,9,295.77859,2,140.828125,[   0 1685]
4,10,488.6982181,2,140.5976563,[   0 1685]
4,11,759.203851,2,140.4755249,[   0 2731]
4,12,779.4935739,2,140.4345093,[   0 1685]
4,13,1342.254902,2,140.3359985,[   0 1685]
4,14,1776.065288,2,140.2845612,[   0 1685]
4,15,2282.000911,2,140.2584457,[   0 1685]
4,16,2862.01994,2,140.246973,[   0 1685]
4,17,3527.409792,2,140.2418842,[   0 1685]
5,1,0.115827322,2,131,[1 2]
5,2,0.545464039,2,157,[0 1]
5,3,0.667226076,2,163,[ 0 39]
5,4,0.80775404,2,159.5,[  1 768]
5,5,0.928613186,2,120,[  1 768]
5,6,3.071434975,2,118.5625,[  1 768]
5,7,5.804346085,2,117.84375,[  1 768]
5,8,11.21379924,2,117.484375,[  1 768]
5,9,21.93690109,2,151,[   0 2941]
5,10,22.78411007,2,142.4453125,[   0 2941]
5,11,43.902004,2,137.2109375,[0 1]
5,12,45.52635598,2,134.4921875,[ 768 2941]
5,13,47.15722609,2,132.5703125,[   0 2941]
5,14,179.0164111,2,130.6484375,[  0 768]
5,15,185.1980453,2,127.7421875,[ 92 768]
5,16,191.5433321,2,126.3212891,[  0 768]
5,17,369.5034301,2,126.1796875,[ 768 1147]
5,18,381.5973229,2,124.0625,[  0 768]
5,19,738.3433201,2,132.1640625,[0 1]
5,20,762.8440921,2,131.8955078,[   0 2941]
5,21,786.8169379,2,131.6806641,[0 1]
5,22,1506.060641,2,131.5769043,[   0 2941]
5,23,1553.698284,2,131.5687256,[0 1]
5,24,2998.610642,2,131.375412,[0 1]

0

In [22]:
import pandas as pd
df_lazy = pd.read_csv("./lazyDelay.csv")
df_lazy.head(20)

,Instance,iteration,time,budget,Obj,interdiction
0,1,1,0.124714,2,163.000000,[0 1]
1,1,2,42.171051,2,163.000000,[0 1]
2,1,3,77.703173,2,218.000000,[ 23 1515]
3,1,4,80.291389,2,197.194336,[1515 2247]
4,1,5,82.939937,2,193.363769,[1515 2247]
5,1,6,152.582776,2,192.581909,[1515 2247]
6,1,7,272.368669,2,192.541748,[1515 2247]
7,1,8,503.612753,2,192.512512,[1515 2247]
8,1,9,949.905776,2,197.194336,[ 23 2247]
9,1,10,983.048546,2,194.987503,[ 23 2247]
10,1,11,1881.867946,2,194.463577,[ 23 2247]
11,1,12,3424.534329,2,194.108105,[ 23 2247]
12,1,1,0.114215,20,163.000000,[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
13,1,2,41.508898,20,163.000000,[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 ...
14,1,3,77.274185,20,295.000000,[ 23 1515 2247 2431 2945 2946 2947 2948 2949 ...
15,1,4,79.851772,20,292.888184,[ 0 1 2 23 157 159 177 842 1002 ...
16,1,5,82.524226,20,242.836426,[ 0 1 2 23 157 159 177 842 1002 ...
17,1,6,153.215141,20,242.752930,[ 0 1 2 23 157 159 177 842 1002 ...
18,1,7,294.128661,20,242.635376,[ 0 1 2 23 157 159 177 842 1002 ...
19,1,8,576.735212,20,242.328781,[ 0 1 2 23 157 159 177 842 1002 ...

In [23]:
import pandas as pd
df_main = pd.read_csv("./main.csv")
df_main.head(20)

,Instance,iteration,time,budget,Obj,interdiction
0,1,1,0.446684,2,222.000000,[1515 2247]
1,1,2,1.027966,2,198.000000,[1515 2247]
2,1,3,2.055484,2,198.000000,[1515 2247]
3,1,4,3.674544,2,198.000000,[1515 2247]
4,1,5,6.403938,2,198.000000,[1515 2247]
5,1,6,11.535572,2,198.000000,[ 23 2247]
6,1,7,12.245661,2,197.359375,[ 23 2247]
7,1,8,21.772698,2,196.398438,[ 23 2247]
8,1,9,38.650715,2,195.917969,[ 23 2247]
9,1,10,68.839330,2,195.609375,[ 23 2247]
10,1,11,122.516219,2,195.278320,[ 23 2247]
11,1,12,224.173950,2,195.008301,[ 23 2247]
12,1,13,422.496325,2,194.824707,[ 23 2247]
13,1,14,804.923709,2,194.600708,[ 23 2247]
14,1,15,1546.272780,2,194.322372,[ 23 2247]
15,1,16,2976.281765,2,194.023537,[ 23 2247]
16,1,1,0.422870,20,295.000000,[ 0 1 2 3 4 5 6 7 8 ...
17,1,2,0.956854,20,295.000000,[ 0 1 2 3 4 5 6 7 8 ...
18,1,3,1.496739,20,295.000000,[ 0 1 2 3 4 5 6 7 8 ...
19,1,4,2.037389,20,295.000000,[ 0 1 2 23 159 1507 1515 1598 1600 ...