In [60]:
import pandas as pd
import os
def processSeqSampling(EXP, N):
    # output = pd.DataFrame(columns="num")
    # output.columns = 
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SeqSampling_N"+str(N)+"_")]
    print(prefixed)
    dfs_list = [pd.read_csv(file, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol','var','opt_gap','iter','para'], header=None) for file in prefixed]
    # print(dfs_list[0])
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    # print(output)
    # for i in range(5):
    #     output = pd.read_csv(EXP+"_N"+str(N)+"_"+str(i+1)+".txt", sep=";", header=None)
        
    return output
def processSAA(EXP, N):
    prefixed = [filename for filename in os.listdir('./') if filename.startswith("SAA_N"+str(N)+"_")]
    dfs_list = [pd.read_csv(file, sep=';', names=['num_cases','total_time','b','ObjVal','x_sol'], header=None) for file in prefixed]
    print(prefixed)
    output = pd.concat(dfs_list, axis=0, ignore_index=True)
    return output

EXP = 'SeqSampling'
N = 10
df_SeqSampling = processSeqSampling(EXP, N)
df_SAA = processSAA(EXP, N)
df_SAA

['SeqSampling_N10_4.txt', 'SeqSampling_N10_5.txt', 'SeqSampling_N10_1.txt', 'SeqSampling_N10_2.txt', 'SeqSampling_N10_3.txt']
['SAA_N10_1.txt', 'SAA_N10_2.txt', 'SAA_N10_3.txt', 'SAA_N10_4.txt', 'SAA_N10_5.txt']

    num_cases  total_time   b      ObjVal                x_sol
0        1000    0.479482   2   76.000000              [ 2 30]
1       10000    4.985736   2   76.000000              [ 2 30]
2       20000    9.914730   2   76.000000              [ 2 30]
3        1000    0.519502   2   76.000000              [ 2 30]
4       10000    4.810937   2   76.000000              [ 2 30]
..        ...         ...  ..         ...                  ...
58      50000   30.830447   2  192.787031              [ 0 18]
59       1000    0.437387  20  230.000000  [ 0  1  3  6 22 18]
60      10000    5.637172  20  230.000000  [ 0  1  3  6 22 18]
61      20000    8.316280  20  230.000000  [ 0  1  3  6 22 18]
62      50000   20.251678  20  230.000000  [ 0  1  3  6 22 18]

[63 rows x 5 columns]

In [63]:
df_SAA[(df_SAA.num_cases ==50000)&(df_SAA.b==2)]

    num_cases  total_time  b      ObjVal    x_sol
6       50000   26.058902  2   76.000000  [ 2 30]
10      50000   25.790386  2   76.000000  [ 2 30]
18      50000   76.267384  2  277.000000  [ 0 18]
22      50000   76.489195  2  277.000000  [ 0 18]
30      50000   61.703715  2  241.078650  [ 4 20]
34      50000   62.795576  2  241.078650  [ 4 20]
42      50000   45.880813  2   66.323960  [ 4 21]
46      50000   46.525756  2   66.323960  [ 4 21]
54      50000   31.046645  2  192.787031  [ 0 18]
58      50000   30.830447  2  192.787031  [ 0 18]

In [64]:
df_SeqSampling

,num_cases,total_time,b,ObjVal,x_sol,var,opt_gap,iter,para
0,49,1.594740,2,35.937095,[4 6],1.203329e+02,6.331572,23,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
1,49,1.387805,2,173.646302,[ 0 22],2.525407e-27,56.000000,20,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
2,49,0.654536,2,76.000000,[ 2 30],1.811915e-30,2.000000,7,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
3,49,0.815751,2,277.000000,[ 0 18],4.529787e-31,1.000000,9,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."
4,49,18.419930,2,232.120182,[4 5],4.798603e+01,57.561440,67,"0.425,0.015,2e-07,1e-07,0.1,8.14491246025,1000..."